<?xml version="1.0" encoding="utf-8"?><Database Name="dbOfficeManagementSystem" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\dbOfficeManagementSystem.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="LINQ_to_SQL.Properties.Settings" SettingsPropertyName="dbOfficeManagementSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblData" Member="tblDatas">
    <Type Name="tblData">
      <Column Name="empId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="empName" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="empCell" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="empAddress" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>